const marketingInternshipPhotos = [
    {
      src: "/cover/GravitiFitnessCover.jpg",
      alt: "Graviti Fitness Cover",
      correspondingPhotos: [
        { src: "/cover/GravitiFitnessCover.jpg", alt: "Alt" },
        { src: "/Graviti/Graviti1.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti2.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti3.jpg", alt: "Picture Cookies" },
        { src: "/Graviti/Graviti4.jpg", alt: "More Cookies" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Graviti/Graviti1.jpg",
      alt: "Graviti Fitness Cover",
      correspondingPhotos: [
        { src: "/cover/GravitiFitnessCover.jpg", alt: "Alt" },
        { src: "/Graviti/Graviti1.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti2.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti3.jpg", alt: "Picture Cookies" },
        { src: "/Graviti/Graviti4.jpg", alt: "More Cookies" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Graviti/Graviti2.jpg",
      alt: "Graviti Fitness Cover",
      correspondingPhotos: [
        { src: "/cover/GravitiFitnessCover.jpg", alt: "Alt" },
        { src: "/Graviti/Graviti1.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti2.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti3.jpg", alt: "Picture Cookies" },
        { src: "/Graviti/Graviti4.jpg", alt: "More Cookies" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Graviti/Graviti3.jpg",
      alt: "Graviti Fitness Cover",
      correspondingPhotos: [
        { src: "/cover/GravitiFitnessCover.jpg", alt: "Alt" },
        { src: "/Graviti/Graviti1.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti2.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti3.jpg", alt: "Picture Cookies" },
        { src: "/Graviti/Graviti4.jpg", alt: "More Cookies" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Graviti/Graviti4.jpg",
      alt: "Graviti Fitness Cover",
      correspondingPhotos: [
        { src: "/cover/GravitiFitnessCover.jpg", alt: "Alt" },
        { src: "/Graviti/Graviti1.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti2.jpg", alt: "Analytics" },
        { src: "/Graviti/Graviti3.jpg", alt: "Picture Cookies" },
        { src: "/Graviti/Graviti4.jpg", alt: "More Cookies" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/cover/ZotfestCover.jpg", //Zotfest start
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/3.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/4.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/5.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/6.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/7.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/8.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/9.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/10.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/11.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/12.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/13.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    {
      src: "/Zotfest/14.png",
      alt: "Zotfest Cover",
      correspondingPhotos: [
        { src: "/cover/ZotfestCover.jpg", alt: "Zotfest Cover Photo" },
        { src: "/Zotfest/3.png", alt: "Zotfest Photo 1" },
        { src: "/Zotfest/4.png", alt: "Zotfest Photo 2" },
        { src: "/Zotfest/5.png", alt: "Zotfest Photo 3" },
        { src: "/Zotfest/6.png", alt: "Zotfest Photo 4" },
        { src: "/Zotfest/7.png", alt: "Zotfest Photo 5" },
        { src: "/Zotfest/8.png", alt: "Zotfest Photo 6" },
        { src: "/Zotfest/9.png", alt: "Zotfest Photo 7" },
        { src: "/Zotfest/10.png", alt: "Zotfest Photo 8" },
        { src: "/Zotfest/11.png", alt: "Zotfest Photo 9" },
        { src: "/Zotfest/12.png", alt: "Zotfest Photo 10" },
        { src: "/Zotfest/13.png", alt: "Zotfest Photo 11" },
        { src: "/Zotfest/14.png", alt: "Zotfest Photo 12" },
      ],
      correspondingVideos: [],
    },
    
  ];

  export default marketingInternshipPhotos;